scripts/dtc: fix multiple definition of yylloc
* After the latest version of GNU Binutils Ubuntu used at 20.04, this
  error has been occuring during kernel builds:
```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x50): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```
  To avoid this, instead of directly defining it, define it externally.

* Commit picked from KakarotKernel/kernel_samsung_7870.

Signed-off-by: Beru Shinsetsu <windowz414@1337.lgbt>